import Link from "next/link";
import { requireAdmin } from "@/modules/auth/presentation/session";
import { getCatalogAdminService } from "@/modules/catalog/infrastructure/catalog-admin-composition";
import { setCategoryActiveAction } from "@/modules/catalog/presentation/catalog-actions";

export const dynamic = "force-dynamic";
export default async function AdminCategoriesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  await requireAdmin("catalog.read"); const [categories, query] = await Promise.all([getCatalogAdminService().listCategories(), searchParams]); const names = new Map(categories.map((category) => [category.id, category.name]));
  return <><div className="admin-heading"><div><p className="eyebrow">Catálogo</p><h1>Categorías</h1><p>Jerarquía, visibilidad y orden del catálogo.</p></div><Link className="button button--dark" href="/admin/categorias/nueva">Nueva categoría</Link></div>{query.error ? <div className="form-error" role="alert">{query.error}</div> : null}<section className="admin-panel admin-table-wrap">{categories.length === 0 ? <div className="empty-state empty-state--small"><h2>Sin categorías</h2></div> : <table className="admin-table"><thead><tr><th>Nombre</th><th>Slug</th><th>Padre</th><th>Orden</th><th>Productos</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{categories.map((category) => <tr key={category.id}><td><strong>{category.name}</strong><small>{category.description ?? "Sin descripción"}</small></td><td>{category.slug}</td><td>{category.parentId ? names.get(category.parentId) ?? "—" : "Raíz"}</td><td>{category.sortOrder}</td><td>{category.productCount}</td><td><span className={`status-badge status-badge--${category.isActive ? "active" : "inactive"}`}>{category.isActive ? "ACTIVA" : "INACTIVA"}</span></td><td><div className="table-actions"><Link href={`/admin/categorias/${category.id}/editar`}>Editar</Link><form action={setCategoryActiveAction}><input name="id" type="hidden" value={category.id} /><input name="active" type="hidden" value={String(!category.isActive)} /><button type="submit">{category.isActive ? "Desactivar" : "Activar"}</button></form></div></td></tr>)}</tbody></table>}</section></>;
}
